Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/BlockLength:
  Max: 300

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'test/*'
    - 'config/*'
    - 'bin/*'
